# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Technical blog about R, block chain and more
description: This site is used for hobby projects about which I write now and then.
baseurl: ""
url: "https://fathomson.github.io/"
permalink: /:year/:month/:day/:title
repository: fathomson/fathomson.github.io
paginate: 5

# theme specific configurations
github_profile: "https://fathomson.github.io"
user: "Frank Thomson"
user_email: "Data Scientist ICT GROUP"
contact_url: "https://goo.gl/hYCr58"
google_tracking_id: "UA-101946097-1"
google_site_verification: "UA-101946097-1"
disqus_shortname: "fathomson"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true


author: Frank Thomson
